### PR TITLE
Log GitHub API Rate Limit and Cache Hit Rate

### LINKED ISSUE #74: API rate limit
bulding currently fails due to this error:

github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for installation ID 33986114.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

How can we fix that?

### PR DESCRIPTION
**Pull request by reneme**
The rate limit seems to be too tight, resulting in failed CI runs.

Closes #74

### CODE REVIEW

**Comment by reneme** [comment]
Currently we're hitting the rate limit despite the cache:

```
INFO:root:Current GitHub API rate limit: 997/1000 (will reset in: 0 hours 58 minutes)
[...]
INFO:root:Performed 2979 API requests (66.4% cache hits)
```

**Comment by sehlen-bsi** [comment]
If this works then you can close #74 with this ;-)

**Comment by reneme** [comment]
Currently, the document contains 418 references to Pull Request and 165 references to commits. Each resource below is fetched exactly once (due to caching)

A back-of-the-envelope calculation:

418 PR Infos + 418 PR Review Infos + 165 Commit Infos + various User Infos -> that'll be more than 1000 requests. 😢

A few options:

1. Partially populate the persistent cache (from failing jobs) and re-run until it passes from the cache
2. Pre-populate the cache from some external source (e.g. a zip archive in the repo)
3. Pay for GitHub Enterprise ([gives 15k requests per hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits))
4. Find a way to fetch the information more efficiently (GitHub provides GraphQL, perhaps that's more flexible)

**Comment by reneme** [comment]
This will be just a quick-fix: The previous (successful) run pre-populated the cache with just a part of the document's topics. Now I'm waiting until about 11:45 for the rate limit to reset. We should then be able to build the remaining topics and the entire document successfully from the partial cache.

That's definitely not a long-term fix, but it'll unblock the build while working on a different document generation strategy.

**Review by lieser — APPROVED** [review]

**Pull request merged**
