### PR TITLE
XMSS Parameter sets and key gen from NIST SP.800-208

### PR DESCRIPTION
**Pull request by reneme**

### CODE REVIEW

**Review by fluppe2 — DISMISSED** [review]
Fine for me, left one comment to be a bit more specific concerning the interoperability when it comes to key and signature generation according to NIST SP 800-208. Also the XMSS public key starts with a four byte identifier of the tree.

**Comment by sehlen-bsi** [comment]
I'm having a hard time figuring out if the changes requested by @fluppe2 have been properly addressed because somehow I can't see the requested changes/comments anymore. Is this due to the force-push or is it just me?

**Comment by lieser** [comment]
@sehlen-bsi The comments are collapsed because @reneme marked them as resolved.

You need to click on *show resolved* button on the right of each resolved comment to see it.

**Comment by sehlen-bsi** [comment]
> @sehlen-bsi The comments are collapsed because @reneme marked them as resolved.
> 
> You need to click on _show resolved_ button on the right of each resolved comment to see it.

Yeah, I've seen this but then, in order to check if a change has been applied I need to manually look at the current version? Is there a more elegant way to do this?

**Comment by reneme** [comment]
Seems that I cannot override the "change requested" review by @fluppe2. 😞
Maybe @sehlen-bsi (as owner of the repository) can merge despite the pending re-review?

**Pull request merged**
